//! Parity against the Electron contract.
//!
//! The unit tests check that each handler does what it means to. These check
//! something different and easier to get wrong: that what it means to do is what
//! the bridge actually promised. A handler can be perfectly correct about the
//! wrong signature — that shipped once, in the fs channels, and every unit test
//! passed because the tests called them the wrong way too.
//!
//! The manifest is the authority. It is generated from `src/preload/index.ts`,
//! so these tests compare the port against the original rather than against a
//! second reading of it.

use serde_json::Value;

fn manifest() -> Value {
    serde_json::from_str(include_str!("../../../../contract/manifest.json"))
        .expect("the manifest is generated by contract/extract-contract.mjs")
}

fn methods() -> Vec<Value> {
    manifest()["methods"].as_array().cloned().unwrap_or_default()
}

fn params_of(name: &str) -> Vec<String> {
    methods()
        .iter()
        .find(|m| m["name"] == name)
        .and_then(|m| m["params"].as_array())
        .map(|ps| ps.iter().filter_map(|p| p["name"].as_str().map(String::from)).collect())
        .unwrap_or_default()
}

/// Every channel is either implemented or deliberately written off. A gap with
/// no decision behind it is the thing this whole exercise exists to prevent.
#[test]
fn every_channel_has_a_decision() {
    let total = md_contract::Rpc::ALL.len();
    let todo = md_server::rpc::unported().len();
    let never = md_server::rpc::not_applicable().len();

    assert_eq!(
        todo, 0,
        "unported channels remain: {:?}",
        md_server::rpc::unported().iter().map(|r| r.as_str()).collect::<Vec<_>>()
    );
    assert_eq!(todo + never + (total - todo - never), total);
}

/// A channel written off must not also have a handler: the dispatcher would
/// refuse something this server can actually serve, invisibly until called.
#[test]
fn nothing_is_both_served_and_written_off() {
    for (rpc, why) in md_server::rpc::not_applicable() {
        assert!(
            md_server::rpc::handler_for(rpc).is_none(),
            "{} is written off ({why}) but has a handler",
            rpc.as_str()
        );
        assert!(!why.is_empty(), "{} is written off with no reason", rpc.as_str());
    }
}

/// The generated channel table must match the manifest it was generated from.
/// If the extractor changes shape, this fails rather than the surface silently
/// shrinking.
#[test]
fn the_channel_table_matches_the_manifest() {
    let counts = &manifest()["counts"];
    assert_eq!(
        md_contract::Rpc::ALL.len() as u64,
        counts["rpcChannels"].as_u64().unwrap(),
        "RPC channel count drifted from the manifest"
    );
    assert_eq!(
        md_contract::Push::ALL.len() as u64,
        counts["pushChannels"].as_u64().unwrap(),
        "push channel count drifted from the manifest"
    );
}

/// Argument ORDER is the part a handler cannot get wrong quietly: a swapped or
/// missing argument produces a plausible-looking failure deep in the operation.
///
/// These are the signatures where the port has actually made that mistake, or
/// where the arguments are similar enough to invite it.
#[test]
fn the_signatures_the_port_reads_positionally_match_the_bridge() {
    // The fs pair — this shipped wrong: handlers read only argument 0.
    assert_eq!(params_of("readFile"), ["root", "rel"]);
    assert_eq!(params_of("writeFile"), ["root", "rel", "content"]);
    assert_eq!(params_of("listDir"), ["root", "rel"]);
    assert_eq!(params_of("readBinary"), ["root", "rel"]);

    // Two strings in a row, where a swap would be silently plausible.
    assert_eq!(params_of("writePty"), ["id", "data"]);
    assert_eq!(params_of("hiveRenameAgent"), ["id", "name"]);
    assert_eq!(params_of("hivePatchAgentRole"), ["id", "role"]);
    assert_eq!(params_of("controlSteer"), ["agentId", "text"]);
    assert_eq!(params_of("skillsInstall"), ["url", "name"]);

    // A boolean second argument, where a swap changes meaning rather than
    // failing.
    assert_eq!(params_of("controlPause"), ["agentId", "on"]);
    assert_eq!(params_of("hiveSetArchived"), ["id", "archived"]);
    assert_eq!(params_of("hiveSetAgentHold"), ["id", "hold"]);
    assert_eq!(params_of("controlGateTool"), ["agentId", "tool", "on"]);

    // Git: cwd first everywhere, then the operation's own arguments.
    for m in ["gitIsRepo", "gitStatus", "gitBranch", "gitBranches", "gitWorktrees"] {
        assert_eq!(params_of(m), ["cwd"], "{m}");
    }
    assert_eq!(params_of("gitDiff"), ["cwd", "relPath"]);
    assert_eq!(params_of("gitShowFile"), ["cwd", "rev", "relPath"]);
    assert_eq!(params_of("gitCompareRefs"), ["cwd", "base", "head", "mode"]);
    assert_eq!(params_of("gitLogGraph"), ["cwd", "n", "skip"]);
}

/// Synchronous IPC has no browser equivalent, so each of these needed a
/// redesign rather than a port. They are served as ordinary calls — the check
/// is that the port knows which ones they are.
#[test]
fn the_synchronous_channels_are_accounted_for() {
    let sync: Vec<String> = methods()
        .iter()
        .filter(|m| m["kind"] == "rpc-sync")
        .filter_map(|m| m["name"].as_str().map(String::from))
        .collect();
    assert_eq!(sync.len(), 3, "the porting notes describe exactly three: {sync:?}");
    for name in &sync {
        assert!(
            ["readClipboardSync", "rosterReadSync", "harnessHomeSync"].contains(&name.as_str()),
            "unexpected synchronous channel {name}"
        );
    }
}

/// The three per-PTY streams are the only channels with a dynamic id in the
/// name. Over one WebSocket they become an envelope carrying the stream id, so
/// the port must know which they are rather than treating every push alike.
#[test]
fn only_the_pty_streams_are_per_instance() {
    let dynamic: Vec<&str> = md_contract::Push::ALL
        .iter()
        .filter(|p| p.is_dynamic())
        .map(|p| p.as_str())
        .collect();
    assert_eq!(dynamic.len(), 3, "{dynamic:?}");
    for d in dynamic {
        assert!(d.starts_with("pty:"), "{d} is dynamic but not a pty stream");
    }
}

/// Push channels the server emits, versus those it does not.
///
/// Not an assertion that all 28 are emitted — eight are not, because their
/// SOURCE is unported (the provider bridges, Electron lifecycle, the mission
/// scheduler). The assertion is that the list of absences is exactly the
/// expected one, so a channel cannot silently stop being emitted.
#[test]
fn the_unemitted_push_channels_are_the_expected_ones() {
    const EXPECTED_ABSENT: [&str; 6] = [
        // Electron lifecycle with no server equivalent.
        "app:closeRequested",
        "power:resume",
        "update:status",
        // Fires from the native file-picker path, which is the client's job.
        "hire:error",
        // Needs the mission scheduler.
        "mission:autoCompact",
        // Needs the voice floor watcher.
        "realtime:floorDelta",
    ];
    // The server source is the authority on what it emits.
    let src = include_str!("../src/handlers.rs").to_string()
        + include_str!("../src/hooks.rs")
        + include_str!("../src/lib.rs")
        + include_str!("../src/ws.rs");

    let mut absent: Vec<&str> = md_contract::Push::ALL
        .iter()
        .filter(|p| !src.contains(&format!("Push::{}", variant(p.as_str()))))
        .map(|p| p.as_str())
        .collect();
    absent.sort_unstable();

    let mut expected = EXPECTED_ABSENT.to_vec();
    expected.sort_unstable();
    assert_eq!(absent, expected, "the set of unemitted push channels changed");
}

/// Mirrors the variant naming in `md-contract`'s build script.
fn variant(channel: &str) -> String {
    channel
        .split([':', '-', '.'])
        .filter(|w| !w.contains('{'))
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
