//! Generate the channel enum from `contract/manifest.json`.
//!
//! With 161 channels, a hand-maintained list drifts from the bridge it mirrors
//! and the drift shows up as 404s in production. Generating the set from the
//! manifest gives a closed enum, parse/serialize that cannot disagree with it,
//! and a basis for measuring port coverage: `md-server` maps `Rpc` to handlers
//! through one function, so "how much is ported" is a query over that mapping
//! rather than a guess.

use std::{collections::BTreeMap, env, fs, path::PathBuf};

#[derive(serde::Deserialize)]
struct Manifest { methods: Vec<Method> }

#[derive(serde::Deserialize)]
struct Method {
    name: String,
    kind: String,
    #[serde(default)] doc: Option<String>,
    channels: Vec<String>,
    #[serde(default)] dynamic: bool,
}

/// `hive:addTask` -> `HiveAddTask`; `pty:data:{id}` -> `PtyData`.
fn variant(channel: &str) -> String {
    let mut out = String::new();
    for part in channel.split([':', '-', '.']) {
        if part.starts_with('{') { continue; }        // the `{id}` hole is not part of the name
        let mut chars = part.chars();
        if let Some(f) = chars.next() {
            out.extend(f.to_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}

fn main() {
    let manifest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../contract/manifest.json");
    println!("cargo:rerun-if-changed={}", manifest_path.display());

    let raw = fs::read_to_string(&manifest_path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", manifest_path.display()));
    let manifest: Manifest = serde_json::from_str(&raw).expect("manifest.json is not valid JSON");

    // Keyed by variant name so duplicates across methods collapse rather than
    // producing two identical enum arms.
    let mut rpc: BTreeMap<String, (String, String, Option<String>)> = BTreeMap::new();
    let mut push: BTreeMap<String, (String, String, bool, Option<String>)> = BTreeMap::new();

    for m in &manifest.methods {
        for ch in &m.channels {
            let v = variant(ch);
            match m.kind.as_str() {
                // `rpc-sync` rides the same request/response path; only the CLIENT
                // differs (it cannot block). Server-side they are identical.
                "rpc" | "rpc-sync" => {
                    rpc.insert(v, (ch.clone(), m.name.clone(), m.doc.clone()));
                }
                "subscription" => {
                    push.insert(v, (ch.clone(), m.name.clone(), m.dynamic, m.doc.clone()));
                }
                _ => {}
            }
        }
    }

    let mut s = String::new();
    s.push_str("// @generated by build.rs from contract/manifest.json — do not edit.\n\n");

    // ---- RPC channels ----
    s.push_str("/// Every request/response channel the client may call.\n");
    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    s.push_str("pub enum Rpc {\n");
    for (v, (ch, method, doc)) in &rpc {
        if let Some(d) = doc {
            for line in d.lines() { s.push_str(&format!("    /// {}\n", line.trim())); }
        }
        s.push_str(&format!("    /// `{ch}` — bridge method `{method}()`\n    {v},\n"));
    }
    s.push_str("}\n\n");

    s.push_str("impl Rpc {\n    pub const ALL: &'static [Rpc] = &[\n");
    for v in rpc.keys() { s.push_str(&format!("        Rpc::{v},\n")); }
    s.push_str("    ];\n\n    pub const fn as_str(self) -> &'static str {\n        match self {\n");
    for (v, (ch, _, _)) in &rpc { s.push_str(&format!("            Rpc::{v} => \"{ch}\",\n")); }
    s.push_str("        }\n    }\n\n");
    s.push_str("    /// Bridge method name this channel came from, for tracing and parity diffing.\n");
    s.push_str("    pub const fn bridge_method(self) -> &'static str {\n        match self {\n");
    for (v, (_, m, _)) in &rpc { s.push_str(&format!("            Rpc::{v} => \"{m}\",\n")); }
    s.push_str("        }\n    }\n\n");
    s.push_str("    pub fn parse(s: &str) -> Option<Rpc> {\n        Some(match s {\n");
    for (v, (ch, _, _)) in &rpc { s.push_str(&format!("            \"{ch}\" => Rpc::{v},\n")); }
    s.push_str("            _ => return None,\n        })\n    }\n}\n\n");

    // ---- Push channels ----
    s.push_str("/// Server-to-client push channels. `dynamic` ones are per-instance\n");
    s.push_str("/// (`pty:data:{id}`) and carry a stream id in the envelope.\n");
    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    s.push_str("pub enum Push {\n");
    for (v, (ch, method, _, doc)) in &push {
        if let Some(d) = doc {
            for line in d.lines() { s.push_str(&format!("    /// {}\n", line.trim())); }
        }
        s.push_str(&format!("    /// `{ch}` — bridge method `{method}()`\n    {v},\n"));
    }
    s.push_str("}\n\n");

    s.push_str("impl Push {\n    pub const ALL: &'static [Push] = &[\n");
    for v in push.keys() { s.push_str(&format!("        Push::{v},\n")); }
    s.push_str("    ];\n\n");
    s.push_str("    /// Channel name, with `{…}` still present for dynamic streams.\n");
    s.push_str("    pub const fn as_str(self) -> &'static str {\n        match self {\n");
    for (v, (ch, _, _, _)) in &push { s.push_str(&format!("            Push::{v} => \"{ch}\",\n")); }
    s.push_str("        }\n    }\n\n");
    s.push_str("    /// True when the channel is per-instance and needs a stream id.\n");
    s.push_str("    pub const fn is_dynamic(self) -> bool {\n        match self {\n");
    for (v, (_, _, dyn_, _)) in &push { s.push_str(&format!("            Push::{v} => {dyn_},\n")); }
    s.push_str("        }\n    }\n\n");
    s.push_str("    pub fn parse(s: &str) -> Option<Push> {\n        Some(match s {\n");
    for (v, (ch, _, _, _)) in &push { s.push_str(&format!("            \"{ch}\" => Push::{v},\n")); }
    s.push_str("            _ => return None,\n        })\n    }\n}\n");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap()).join("channels.rs");
    fs::write(&out, s).unwrap();
}
